### ISSUE TITLE
[Feat] 一些翻译建议

### ISSUE THREAD

**Issue by SummonHIM** [HK417KEN/Lethal_Company_Simplified_Chinese_Localization#1]
有一句漏翻译。不知道是不是新加的。因为我看[BepInEx/config/Translation/zh/MainMenu.txt#L74](https://github.com/HK417KEN/Lethal_Company_Simplified_Chinese_Localization/blob/master/BepInEx/config/Translation/zh/MainMenu.txt#L74)也确实有相似的

![屏幕截图 2024-01-10 100819](https://github.com/HK417KEN/Lethal_Company_Simplified_Chinese_Localization/assets/33192611/bc389225-1ab9-475b-8a5d-53ece31c290e)

字体建议
建议[BepInEx/config/AutoTranslatorConfig.ini#L38](https://github.com/HK417KEN/Lethal_Company_Simplified_Chinese_Localization/blob/master/BepInEx/config/AutoTranslatorConfig.ini#L38)中`OverrideFontTextMeshPro`选项留空，仅使用`FallbackFontTextMeshPro`字体。这样子英文字符使用原版字体排版会更美观

![屏幕截图 2024-01-10 100647](https://github.com/HK417KEN/Lethal_Company_Simplified_Chinese_Localization/assets/33192611/ba241c21-6cd7-494e-bfd6-cdbe435b77e0)
![屏幕截图 2024-01-10 100140](https://github.com/HK417KEN/Lethal_Company_Simplified_Chinese_Localization/assets/33192611/815787c3-cb09-41f8-8d77-e2734b320480)
![屏幕截图 2024-01-10 100954](https://github.com/HK417KEN/Lethal_Company_Simplified_Chinese_Localization/assets/33192611/4a3e2e5b-9ec0-4052-98b5-c1b0b48c3a82)

**Comment by HK417KEN** [comment]
你好，提示语确实是被近几个游戏补丁修改了的；新的修改已经提交上去了，Thunderstore网站可能需要数分钟时间更新，r2modman可能会需要十多分钟，稍等一下就好了。

感谢您的反馈！

**Comment by SummonHIM** [comment]
忘记了 关于那个字体变黑的问题
![image](https://github.com/HK417KEN/Lethal_Company_Simplified_Chinese_Localization/assets/33192611/01fe97db-13a5-430a-8645-cb69f43dd852)

Unity的字体有个SDF渲染技术。就是把字体描边描糊来达到高清字体的效果。但是在这个游戏里面使用的时候会把这个模糊描边填充成黑色。原因我也不是很了解。

制作字体我也是从这里学的：https://www.bilibili.com/read/cv16479815/

这是我自己打包的[霞鹜文楷体](https://github.com/lxgw/LxgwWenKai)。可以参考下

![image](https://github.com/HK417KEN/Lethal_Company_Simplified_Chinese_Localization/assets/33192611/182a83f6-ffed-4d26-9408-2bfdbe56eb31)

但实际上有些问题就是这字体太细了。走远了有些字会变成方块。如果没安装高清包情况会更严重

**Comment by SummonHIM** [comment]
还有一些之前翻的模组的翻译也顺便贴上来把
```
# Meme Soundboard
Soundboard=播放器
r:"^Next Sound\s*:\s*(.+)(.+)$"=下一声音：$1$2
r:"^Previous Sound\s*:\s*(.+)(.+)$"=上一声音：$1$2
Grab - Play Meme Sounds!=拿取 - 播放 Meme 音效！

# MoreEmotes
r:"Middle Finger\n\[(.+)\]"=中指\n[$1]
r:"Clap\n\[(.+)\]"=拍手\n[$1]
r:"Shy\n\[(.+)\]"=害羞\n[$1]
r:"The Griddy\n\[(.+)\]"=格迪舞\n[$1]
r:"Twerk\n\[(.+)\]"=摇臀舞\n[$1]
r:"Salute\n\[(.+)\]"=敬礼\n[$1]

# LethalExpansion
> Mod Settings=> 模组设置
Mod Settings :=模组设置 :
Compatibility:=兼容性：
Debug:=调试：
Dungeons:=工厂：
Expeditions:=探险：
Lobby:=大厅：
Modules:=模块
Moons:=星球：
Time:=时间：
Default=默认
All Default=恢复全部为默认
Apply=应用
r:"Network synchronization: (.+)\nMod required by clients: (.+)"=联机同步：$1\n模组要求与其他玩家一致：$2

Change the global time speed=更改总时间速度。
r:"^Max lenght of an Expedition in hours. \(Begin at 6 AM \| 18 = Midnight\)$"=最大探险持续时间（从早上6点开始 | 18 = 午夜）
Change amount of days for the Quota.=更改目标金额的天数。
Change amount of starting Credit.=更改起始余额。
Change the Cost of the Moon Routes.=更改星球路线的费用。
Change the starting Quota.=更改起始目标金额。
Change the amount of Scraps in dungeons.=更改地牢中的物品数量。
Change the value of Scraps.=更改物品的价值。
Change the size of the Dungeons. (Can crash when under 1.0)=更改地牢的大小。（小于1.0时可能崩溃）
Prevent Landmines to explode by dropping items on them=通过放置物品防止地雷爆炸
r:"^Set the minimal weight to prevent Landmine's explosion \(0\.15 .* 16 lb, Player .* 2\.0\)$"=设置防止地雷爆炸的最小重量（0.15 \= 16磅，玩家 \= 2.0）
r:"^Change the carried Weight unit : 0 .* Pounds \(lb\), 1 .* Kilograms \(kg\) and 2 .* Both$"=更改携带的重量单位：0 \= 磅（lb），1 \= 千克（kg），2 \= 两者都有
r:"^Convert Pounds into Kilograms \(16 lb .* 7 kg\) \(Only effective if WeightUnit .* 1\)$"=将磅转换为千克（16磅 \= 7千克）（仅在WeightUnit \= 1时有效）
Prevent the Scraps Wipe when all players die.=防止所有玩家死亡时清除物品。
Display a 24h clock instead of 12h.=显示24小时时钟而不是12小时。
Display clock while inside of the Ship.=在船内显示时钟。
Automatically increase the Deadline depending of the required quota.=根据所需的目标金额自动增加截止日期。
Increase the quota deadline of one day each time the quota exceeds this value.=每次目标金额超过此值时，增加一天的目标金额截止日期。
Load SDK Modules that add new content to the game. Disable it to play with Vanilla players. (RESTART REQUIRED)=加载添加新内容的SDK模块。禁用它以与原版玩家一起游玩。（需要重新启动）
Change the Items cap can be kept in the ship.=更改可以在船上保留的物品上限。
Display the current weather of Moons in the Terminal's Moon Catalogue.=在终端的星球目录中显示星球的当前天气。
Display the rank of Moons in the Terminal's Moon Catalogue.=在终端的星球目录中显示星球的等级。
Display the route price of Moons in the Terminal's Moon Catalogue.=在终端的星球目录中显示星球路线的价格。
r:"^Change the Quota Increase Steepness. \(Highter .* less steep exponential increase\)$"=更改目标金额增加的陡峭度。（越高 \= 指数增加较小）
Change the Quota Base Increase.=更改目标金额基础增加。
Kick the players without Lethal Expansion installer. (Will be kicked anyway if LoadModules is True)=踢掉没有 Lethal Expansion 模组的玩家。（如果LoadModules为True，仍将被踢掉）
Leave Brutal Company Plus control the Quota settings.=让 Brutal Company Plus 控制目标金额设置。
Leave Lethal Adjustments control the Dungeon settings.=让 Lethal Adjustments 控制地牢设置。
Let Coomfy Dungeons control the Dungeon size & scrap settings.=让 Coomfy Dungeons 控制地牢的大小和物品设置。
Let MoreMoneyStart control the Starting credits amount.=让 MoreMoneyStart 控制起始余额。
Show an output of every settings in the Console. (The Console must listen Info messages)=在控制台中显示每个设置的输出。（控制台必须监听信息消息）

# ObjectVolumeController
r:"^Grab boombox:.*\[(.+)\]\n(\d+)% volume\nVolume up:.*\[(.+)\]\nVolume down:.*\[(.+)\]"=捡起音响 [$1]\n音量 $2%\n提高音量 [$3]\n降低音量 [$4]
r:"^(\d+)% volume\nVolume up:.*\[(.+)\]\nVolume down:.*\[(.+)\]"=音量 $1%\n提高音量 [$2]\n降低音量 [$3]

```

**Comment by HK417KEN** [comment]
字体的问题有点麻烦,，霞鹜文楷体确实还是太细了，之后有机会再试别的字体吧。

MoreEmotes 的翻译试了下不好使，可能更新了之后用不了，试着调整下正则也不太行所以没更新这个。其他的mod的翻译已经更新了。

非常感谢！

**Comment by SummonHIM** [comment]
一些未翻译补充

这个key不知道是怎么问题是弄不了的
![20240112230651_1](https://github.com/HK417KEN/Lethal_Company_Simplified_Chinese_Localization/assets/33192611/1cfd52f3-e6b6-4dde-a4d1-3a6ed191f8eb)

还有一个罐头食物，忘记截图了

一些警告。不过是上个版本的了
```
Got scrap!\nTo sell, use the terminal to route the ship to the company building.=捡到东西了！\n若要出售。使用终端来导航飞船至公司大楼。
TIP:\nUse the ship computer terminal to access secure doors.=提示：\n使用飞船电脑终端来解锁安全门。
HALT!\nYou have 0 days left to meet the quota. Use the terminal to route to the company and sell.=快停下！\n你只剩 0 天的时间去完成目标金额了。使用终端来导航飞船至公司大楼出售物品。
ALERT!\nDrop your metallic items now! A static charge has been detected. You have seconds left to live.=警告！\n立即放下金属物品！检测到静电荷。您只剩下几秒钟的生命了。
```

显示公斤的是LE的功能
```
r:"^([0-9]+) kg$"=$1 千克
r:"^([0-9]+) kg\n([0-9]+) lb$"=$1 千克\n$2 磅
```

**Comment by SummonHIM** [comment]
![20240113213001_1](https://github.com/HK417KEN/Lethal_Company_Simplified_Chinese_Localization/assets/33192611/7dc08529-5e67-4ce7-b2f1-ad7aa32417df)
![20240113213005_1](https://github.com/HK417KEN/Lethal_Company_Simplified_Chinese_Localization/assets/33192611/d11d5e9d-4023-4d27-b0ab-08ac6e5ff418)
 一些补充

**Comment by HK417KEN** [comment]
本项目已经弃用了，感谢支持，请使用其他汉化Mod代替，谢谢！

建议使用这个汉化Mod：
- [Lethal Company Simplified Chinese Localization](https://thunderstore.io/c/lethal-company/p/SweetFox/Lethal_Company_Simplified_Chinese_Localization/) by  [SweetFox](https://thunderstore.io/c/lethal-company/p/SweetFox/)

真的非常感谢和你一起完善汉化，希望可以有缘再见！
