### ISSUE TITLE
终端汉化建议

### ISSUE THREAD

**Issue by Ascensus-31** [HK417KEN/Lethal_Company_Simplified_Chinese_Localization#3]
如果加了LethalExpansion新的星球，终端汉化后会找不到新增的星球，蛋炒饭的那个汉化也是这样的。

**Comment by HK417KEN** [comment]
你好，建议移步到 [终端汉化项目](https://github.com/HK417KEN/Lethal_Company_Simplified_Chinese_Terminal_Localization) 里报告这类问题，不过现在也没多少 issuse 所以暂时没关系。

终端的汉化基于的 NewTerminal 中的星球列表，这个几乎是静态的写死的，列表并不能随着别的mod变化而变化。为了不让其他玩家感到困惑，我就不写上其他mod的星球了，除非能够做出动态化的列表后我就再更新上去。

如果你想自己修改这个列表请到 ```BepInEx\config\NewTerminal-Other.cfg``` 文件中约138行的 ```Moons = xxx``` 中自行添加和修改。分享这个修改给朋友则可以通过 r2modman 或直接传文件覆盖，但如果是星球mod的制作者想要兼容那现阶段建议自行添加和维护 NewTerminal 的内容。

**Comment by HK417KEN** [comment]
本项目已经弃用了，感谢支持，请使用其他汉化Mod代替，谢谢！

建议使用这个汉化Mod：
- [Lethal Company Simplified Chinese Localization](https://thunderstore.io/c/lethal-company/p/SweetFox/Lethal_Company_Simplified_Chinese_Localization/) by  [SweetFox](https://thunderstore.io/c/lethal-company/p/SweetFox/)
