### ISSUE TITLE
部分原有英文位置不显示汉化

### ISSUE THREAD

**Issue by LionYu66** [HK417KEN/Lethal_Company_Simplified_Chinese_Localization#4]
![image](https://github.com/HK417KEN/Lethal_Company_Simplified_Chinese_Localization/assets/51237029/562253d1-7b43-4b80-930a-fb0b0a8e34b8)
如图黄色弹窗位置

**Comment by HK417KEN** [comment]
这个是 XUnity.AutoTranslator 的问题，我无力解决，抱歉

**Comment by HK417KEN** [comment]
本项目已经弃用了，感谢支持，请使用其他汉化Mod代替，谢谢！

建议使用这个汉化Mod：
- [Lethal Company Simplified Chinese Localization](https://thunderstore.io/c/lethal-company/p/SweetFox/Lethal_Company_Simplified_Chinese_Localization/) by  [SweetFox](https://thunderstore.io/c/lethal-company/p/SweetFox/)

您的这个问题用这个 Mod 是可以解决的。
