### ISSUE TITLE
用了该汉化后，Ozone的Glow_Steps这个MOD报错

### ISSUE THREAD

**Issue by niuit0** [HK417KEN/Lethal_Company_Simplified_Chinese_Localization#6]
作者您好，使用该汉化MOD后，荧光脚步MOD不可用。

该MOD相关输出：
```
[Info   :   BepInEx] Loading [BepInUtils 1.2.1]
[Info   :BepInUtils] System loaded.
[Info   :   BepInEx] Loading [Glow Steps 1.1.2]
[Info   :Glow Steps] [Production] Patched class FootstepPatcher, containing 2 methods.

[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
NicholaScott.LethalCompany.GlowSteps.FootstepPatcher.AddPositionToTracking (GameNetcodeStuff.PlayerControllerB __instance) (at <884ecf5ae2e54df3bda7999913d264b9>:0)
(wrapper dynamic-method) GameNetcodeStuff.PlayerControllerB.DMD<GameNetcodeStuff.PlayerControllerB::PlayFootstepSound>(GameNetcodeStuff.PlayerControllerB)
GameNetcodeStuff.PlayerControllerB.PlayFootstepLocal () (at <af9b1eec498a45aebd42601d6ab85015>:0)
PlayerAnimationEvents.PlayFootstepLocal () (at <af9b1eec498a45aebd42601d6ab85015>:0)
```

使用英文是正常的，是汉化MOD和荧光脚步这个MOD冲突？

**Comment by HK417KEN** [comment]
你好，请排查其他mod的冲突，我只用 Glow_Steps 和 汉化Mod 时是可以显示脚印的


![GlowStepsTest](https://github.com/HK417KEN/Lethal_Company_Simplified_Chinese_Localization/assets/20549116/e5df7767-4dc8-4ee8-905e-1e8b902632aa)

![20240114112614_1](https://github.com/HK417KEN/Lethal_Company_Simplified_Chinese_Localization/assets/20549116/6763f54e-950a-40c1-aad1-e42e2c1ed233)

**Comment by niuit0** [comment]
果真是，感谢作者回复，我再排查排查。

**Comment by HK417KEN** [comment]
本项目已经弃用了，感谢支持，请使用其他汉化Mod代替，谢谢！

建议使用这个汉化Mod：
- [Lethal Company Simplified Chinese Localization](https://thunderstore.io/c/lethal-company/p/SweetFox/Lethal_Company_Simplified_Chinese_Localization/) by  [SweetFox](https://thunderstore.io/c/lethal-company/p/SweetFox/)
