### ISSUE TITLE
字体相关建议

### ISSUE THREAD

**Issue by lostone-zc** [HK417KEN/Lethal_Company_Simplified_Chinese_Localization#7]
你也许可以参考 [github](https://github.com/lekakid/LC-FontPatcher/tree/main) [thunderstore](https://thunderstore.io/c/lethal-company/p/LeKAKiD/FontPatcher/) 这个来更改游戏内字体？

**Comment by HK417KEN** [comment]
好的谢谢，我再看一下

**Comment by HK417KEN** [comment]
本项目已经弃用了，感谢支持，请使用其他汉化Mod代替，谢谢！

建议使用这个汉化Mod：
- [Lethal Company Simplified Chinese Localization](https://thunderstore.io/c/lethal-company/p/SweetFox/Lethal_Company_Simplified_Chinese_Localization/) by  [SweetFox](https://thunderstore.io/c/lethal-company/p/SweetFox/)

请用这个 汉化Mod 这个汉化可以更全面！
