### ISSUE TITLE
加载本mod后启动会报错，且邀请好友界面会被置顶且鼠标点击不到，无法关闭或退出

### ISSUE THREAD

**Issue by XinFengAndy** [HK417KEN/Lethal_Company_Simplified_Chinese_Localization#8]
win10系统，在取消加载其他mod，仅加载前置mod（BepInExPack）和本mod时（如下图1），在r2modman中点击start modded后会一直报错（如下图2），进入游戏后在邀请好友界面弹出的steam的选择要邀请的好友窗口会比正常的大，而且指针及游戏画面都在这个窗口之下（如下图3），无法通过点击（指针在窗口底下），esc键（没有反应）来关闭该窗口，只有选择关闭r2modman打开的cmd窗口强制关闭游戏来结束。
![1](https://github.com/HK417KEN/Lethal_Company_Simplified_Chinese_Localization/assets/37838294/f2c75fce-7c14-4ccb-aa77-78a31dafc432)
![7cf7d40721d4f2dcecaa3b630d0d054](https://github.com/HK417KEN/Lethal_Company_Simplified_Chinese_Localization/assets/37838294/4c3880ee-ec44-44f1-95fa-a5357da25123)
![image](https://github.com/HK417KEN/Lethal_Company_Simplified_Chinese_Localization/assets/37838294/3a19cfa7-a6a8-4926-a67a-cb68bcd4f817)

**Comment by HK417KEN** [comment]
本项目已经弃用了，感谢支持，请使用其他汉化Mod代替，谢谢！

建议使用这个汉化Mod：
- [Lethal Company Simplified Chinese Localization](https://thunderstore.io/c/lethal-company/p/SweetFox/Lethal_Company_Simplified_Chinese_Localization/) by  [SweetFox](https://thunderstore.io/c/lethal-company/p/SweetFox/)

以下是您的问题的回答：

1. 控制台报错请看该回答 [#2](https://github.com/HK417KEN/Lethal_Company_Simplified_Chinese_Localization/issues/2#issuecomment-1885778242)
2. Steam覆盖层的界面现已修复（邀请好友的字体大小和无法关闭的问题）
